name: tv_sink
description: A new Flutter project.

version: 1.0.27+27

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_string: ^3.0.1
  scrollable_positioned_list: ^0.2.3
  cached_network_image: ^3.2.0
  transparent_image: ^2.0.0
  package_info_plus: ^8.1.0
  connectivity_plus: ^6.1.0
  open_file: ^3.5.9
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.2+1
  share_plus: ^10.0.3
  google_mobile_ads: ^4.0.0

  fijkplayer: ^0.11.0
  video_player_media_kit: ^1.0.5
  media_kit_libs_macos_video: any

  flutter_easyloading: ^3.0.5
  logger: ^1.1.0
  retry: ^3.1.2
  supabase: ^2.5.0
  dio: ^5.7.0
  shared_preferences: ^2.0.13
  #状态管理
  get: ^4.6.6
  permission_handler: 11.3.1
  path_provider: ^2.0.9
  flutter_update_dialog: ^2.0.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  branding: "images/splash_icon.png"
  color: "#ffffff"
  branding_mode: bottom
#  background_image : "images/startup.png"
  ardroid: true
  ios: true